INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (1, 'Água Morna', 'Centro', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (2, 'Cercado Grande', 'Centro', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (3, 'Embuema', 'Centro', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (4, 'Jardim De Lourdes', 'Centro', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (5, 'Jardim Ferreira', 'Centro', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (6, 'Jardim Novo Embu', 'Centro', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (7, 'Jardim Santa Maria', 'Centro', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (8, 'Maria Auxiliadora', 'Centro', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (9, 'Parque Francisco Rizzo', 'Centro', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (10, 'Tingidor', 'Centro', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (11, 'Vila Bonfim', 'Centro', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (12, 'Esplanada Oliveiras', 'Centro', 'Oliveiras');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (13, 'Jardim Dos Oliveiras', 'Oliveiras', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (14, 'Cooperativa', 'Parque Industrial', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (15, 'Gramado', 'Parque Industrial', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (16, 'Granja Nossa Senhora Aparecida', 'Parque Industrial', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (17, 'Jardim Elisa', 'Parque Industrial', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (18, 'Jardim Lavorato', 'Parque Industrial', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (19, 'Jardim Magaly', 'Parque Industrial', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (20, 'Jardim Sadie', 'Parque Industrial', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (21, 'Jardim Santa Barbara', 'Parque Industrial', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (22, 'Pataxós', 'Parque Industrial', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (23, 'Embu-Mirim', 'Pinheirinho', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (24, 'Jardim Pinheirinho', 'Pinheirinho', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (25, 'Jardim Pinheiros', 'Pinheirinho', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (26, 'Jardim Santo Antônio', 'Pinheirinho', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (27, 'Parque Industrial', 'Pinheirinho', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (28, 'Quinta Do Morro', 'Pinheirinho', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (29, 'Água Espraiada', 'Quinhau', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (30, 'Chácaras Lídia', 'Quinhau', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (31, 'Engenho Velho', 'Quinhau', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (32, 'Quinhau', 'Quinhau', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (33, 'Jardim Santa Clara', 'Santa Clara', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (34, 'Maria Imaculada', 'Santa Clara', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (35, 'Jardim Mimás', 'Vista Alegre', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (36, 'Jardim Vista Alegre', 'Vista Alegre', 'Centro');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (37, 'Jardim Angela', 'Ângela-Batista', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (38, 'Jardim Batista', 'Ângela-Batista', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (39, 'Jardim Da Luz', 'Ângela-Batista', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (40, 'Jardim Santa Rita', 'Ângela-Batista', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (41, 'Jardim Castilho', 'Castilho', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (42, 'Jardim Florida', 'Castilho', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (43, 'Jardim São Luiz', 'Castilho', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (44, 'Vila Perequê', 'Castilho', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (45, 'Jardim Do Colégio', 'Colégio-São Marcos', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (46, 'Jardim Dos Moraes', 'Colégio-São Marcos', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (47, 'Jardim São Francisco', 'Colégio-São Marcos', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (48, 'Jardim São Marcos', 'Colégio-São Marcos', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (49, 'Parque Das Chácaras', 'Colégio-São Marcos', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (50, 'Jardim Dom José', 'Dom José-Santo Eduardo', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (51, 'Jardim Santo Eduardo', 'Dom José-Santo Eduardo', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (52, 'Jardim Taima', 'Dom José-Santo Eduardo', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (53, 'Jardim Casa Branca', 'Independência', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (54, 'Jardim Fabiana', 'Independência', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (55, 'Jardim Independência', 'Independência', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (56, 'Jardim Júlia', 'Independência', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (57, 'Jardim Marina', 'Independência', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (58, 'Jardim Vitória', 'Independência', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (59, 'Santa Rosa', 'Independência', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (60, 'Jardim Nayara', 'Nossa Senhora De Fátima', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (61, 'Jardim Nossa Senhora De Fátima', 'Nossa Senhora De Fátima', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (62, 'Parque Luiza', 'Nossa Senhora De Fátima', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (63, 'Vila Isis Cristina', 'Pirajussara', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (64, 'Parque Pirajussara', 'Pirajussara', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (65, 'Jardim Irene', 'Santa Emilia', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (66, 'Jardim Novo Campo Limpo', 'Santa Emilia', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (67, 'Jardim Presidente Kennedy', 'Santa Emilia', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (68, 'Jardim Santa Emília', 'Santa Emilia', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (69, 'Paranapanema', 'Santa Emilia', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (70, 'Jardim Laila', 'Santa Tereza', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (71, 'Jardim Santa Tereza', 'Santa Tereza', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (72, 'Vila Olinda', 'Santa Tereza', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (73, 'Vila Regina', 'Santa Tereza', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (74, 'Jardim Jurema', 'Vazame', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (75, 'Jardim Valo Verde', 'Vazame', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (76, 'Jardim Vazame', 'Vazame', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (77, 'Vila Carmem', 'Vazame', 'Leste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (78, 'Bosque Capuava', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (79, 'Bosque Do Embu', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (80, 'Caminho Do Índio', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (81, 'Capuava', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (82, 'Chácaras Ana Lúcia', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (83, 'Chácaras Bartira', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (84, 'Chácaras São Cristóvão', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (85, 'Invernada', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (86, 'Itatuba', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (87, 'Jardim Dos Ipês', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (88, 'Jardim Indaiá', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (89, 'Maranhão', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (90, 'Parque Dos Caetés', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (91, 'Parque Sao Leonardo', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (92, 'Pedreira', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (93, 'Perovê', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (94, 'Ponta Porã', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (95, 'Vale Do Sol', 'Capuava-Itatuba', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (96, 'Estância De Embuarama', 'Moinho Velho', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (97, 'Jardim Colibri', 'Moinho Velho', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (98, 'Jardim Recanto Da Fonte', 'Moinho Velho', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (99, 'Jardim Santa Luzia', 'Moinho Velho', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (100, 'Jardim Silvia', 'Moinho Velho', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (101, 'Jardim Tomé', 'Moinho Velho', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (102, 'Moinho Real', 'Moinho Velho', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (103, 'Moinho Velho', 'Moinho Velho', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (104, 'Prado Rangel', 'Moinho Velho', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (105, 'Vila Real', 'Moinho Velho', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (106, 'Chácaras Aurora', 'Ressaca', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (107, 'Embu Colonial', 'Ressaca', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (108, 'Jardim Itatiaia', 'Ressaca', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (109, 'Pindorama', 'Ressaca', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (110, 'Ressaca', 'Ressaca', 'Oeste');
INSERT INTO zona (id, bairro, unidade_administrativa, regiao) VALUES (111, 'Votorantim', 'Ressaca', 'Oeste');